[package]
name = "tm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "tm_cli"
path = "src/lib.rs"

[[bin]]
name = "tm-cli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
tm-core = { path = "../tm-core" }

[lints]
workspace = true
